### ISSUE TITLE
I would not recommend using Telegraf as Grammy is more developer friendly))

### ISSUE THREAD

**Issue by uwussimo** [vladilenm/tgbot-gpt#1]

**Comment by uwussimo** [comment]
https://grammy.dev/

**Comment by vladilenm** [comment]
what is the main reason to switch? they have really same api

**Comment by uwussimo** [comment]
I mean, yeah that's true though...

Regarding your question about the main reason to switch from Telegraf to GrammY, while both libraries have similar APIs, there are several reasons why someone might consider switching. These include better performance, scalability, a more modular design, a strongly typed API, and active development and community support.
